# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    images_directory: %kernel.root_dir%/../web/uploads/media
services:
    appbundle.fileuploader:
        class: AppBundle\Service\FileUploader
        arguments: [ @doctrine.orm.entity_manager, @request_stack, @validator, @kernel ]