services:

    sonata.admin.home:
        class: AppBundle\Admin\HomeAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "Beiträge"
              label: "Home"
              label_catalogue: "AppBundle"
        arguments:
            - ~
            - AppBundle\Entity\Home
            - ~

    sonata.admin.fotografen:
            class: AppBundle\Admin\FotografenAdmin
            tags:
                - name: sonata.admin
                  manager_type: orm
                  group: "Fotografen"
                  label: "Fotografen"
                  label_catalogue: "AppBundle"
            arguments:
                - ~
                - AppBundle\Entity\Fotografen
                - ~